apiVersion: v1
kind: ConfigMap
metadata:
  name: https-nginx-config
  namespace: {{ .Release.Namespace }}
data:
  nginx.conf: |
    worker_processes  1;
    events {
        worker_connections  1024;
    }
    http {
        sendfile           on;
        keepalive_timeout  65;
        server {
          listen                    8443 ssl;
          server_name               localhost;
          ssl_certificate           /app/cert/tls.crt;
          ssl_certificate_key       /app/cert/tls.key;
          ssl_protocols             TLSv1.2 TLSv1.3;
          ssl_ciphers               AESGCM:CHACHA20:-kRSA:-aNULL;
          ssl_prefer_server_ciphers on;
          ssl_ecdh_curve            X25519:prime256v1;
          ssl_dhparam               /tmp/ssl/ffdhe2048.pem;
          location / {
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $http_host;
            proxy_pass       http://127.0.0.1:8080/;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
          }
        }
    }
---
# this file is from https://ssl-config.mozilla.org/ffdhe2048.txt
apiVersion: v1
data:
  ffdhe2048.pem: |-
    -----BEGIN DH PARAMETERS-----
    MIIBCAKCAQEA//////////+t+FRYortKmq/cViAnPTzx2LnFg84tNpWp4TZBFGQz
    +8yTnc4kmz75fS/jY2MMddj2gbICrsRhetPfHtXV/WVhJDP1H18GbtCFY2VVPe0a
    87VXE15/V8k1mE8McODmi3fipona8+/och3xWKE2rec1MKzKT0g6eXq8CrGCsyT7
    YdEIqUuyyOP7uWrat2DX9GgdT0Kj3jlN9K5W7edjcrsZCwenyO4KbXCeAvzhzffi
    7MA0BM0oNC9hkXL+nOmFg/+OTxIy7vKBg8P+OxtMb61zO7X8vC7CIAXFjvGDfRaD
    ssbzSibBsu/6iGtCOGEoXJf//////////wIBAg==
    -----END DH PARAMETERS-----
kind: ConfigMap
metadata:
  name: https-nginx-dhparams
  namespace: {{ .Release.Namespace }}
