apiVersion: v1
kind: ConfigMap
metadata:
  name: http-nginx-config
  namespace: {{ .Release.Namespace }}
data:
  nginx.conf: |
    worker_processes  1;
    events {
        worker_connections  1024;
    }
    http {
        sendfile           on;
        keepalive_timeout  65;
        server {
          listen                    8080;
          server_name               localhost;
          location / {
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $http_host;
            proxy_pass       http://127.0.0.1:8081/;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
          }
        }
    }
